</td>
		<td width="30">
			
		</td>
		<td width="220">
			< img src="./song.jpg" width="148">
		</td>
	
		
		<td width="500">
			<font face="Arial"> <b><font size="5">Peiyan Song</font></b><p>
			Professor </p ></font><p><font face="Arial">
			Department of Data Science,Management School,Tianjin Normal University<br>
			<br>
			Address:Room B520, Building XINGWEN, No.393, Binshui West Road, Xiqing District, Tianjin, China<br>
                        Post Code: 300380 <br>
			Phone Number: (+86) 18822339368 <br>
			Email: <font size="2"><b> spyer2008@126.com</b></font></font>
							
		</p ></td>
	</tr>
	<tr>
		<td width="50">
		</td>
		<td colspan="3" align="left" height="20" valign="top" width="750">
			<hr>
		</td>
	</tr>
	<tr>
		<td width="50">
		</td>
		<td colspan="3" align="left" height="20" valign="top" width="750">
			
			I am a Professor ....
			
			<h3>Research</h3>
			
			My research interests... 
			
            <!--<h3>Research Group: ONE(WAN) NLP Group </h3>-->
            
			<h3>Publications</h3>
			
			My publication...

            <h3>Honors and Awards</h3>
			<ul>
              <li>  <b>Distinguished Paper Award, IJCAI 2018 </b> </li>
              <li>  <b>Outstanding Paper Award, ACL 2017 </b> </li>
              <li>  Tsang Hin-chi Faculty Fellowship Award, 2019 </li>
              <li>  PKU Teaching Excellence Award, 2019 </li>
              <li>  PKU Industry-Academy-Research (ChanXueYan) Cooperation Award, 2019 </li>
              <li>  PKU Yang&Wang Faculty Fellowship Award, 2018 </li>
              <li>  CCF NLPCC Distinguished Young Scientist, 2017 </li> 
              <li>  CAAI WUWENJUN Technical Innovation Award, 2017 </li> 
              <li>  IBM Faculty Award, 2015 </li>
			  <li>  PKU Baosteel Faculty Fellowship Award, 2013 </li>
			  <li>  PKU "WangXuan" Young Investigator Award, 2010 </li>
              <li>  Best Reviewer, EMNLP 2010 </li>
              <li>  Excellent Doctoral Dissertation of PKU, 2009 </li>
              <li>  PKU P&G Faculty Fellowship Award, 2008 </li>
              <li>  Recipient of Beijing Nova Program, 2008 </
